#!/bin/bash
#--------------------------------------------------------------------------
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#--------------------------------------------------------------------------
# To enable this hook, rename this file to "pre-commit".
#--------------------------------------------------------------------------
# This pre-commit hook validates your files for ESLint and Stylelint issues
# If any issues are found, the commit you made will be rejected.
#--------------------------------------------------------------------------

set -e

if grep -r "eslint-disable" src/; 
then
    echo "Your code disabled some eslint rules please enable the rules and fix the issues"
    exit 1
fi

npx eslint "src/**/*.{js,jsx,ts,tsx}" --max-warnings 0 --no-error-on-unmatched-pattern
eslint_exit_code=$?

if [ $eslint_exit_code -ne 0 ]
then
  echo "Your code has ESLint errors. Resolve them before committing the code."
  exit 1
fi

npx stylelint src/**/*.css src/**/*.scss --allow-empty-input
stylelint_exit_code=$?

if [ $stylelint_exit_code -ne 0 ]
then
  echo "Your code has Stylelint errors. Resolve them before committing the code."
  exit 1
fi

unused_export_count=$(npx ts-prune --ignore "src\index|src/index" | wc -l)

if [ $unused_export_count -ne 0 ]
then
  echo "Your code has $unused_export_count unused exports. Remove them before committing the code."
  echo "Run 'npx ts-prune' to identify the unused exports"
  exit 1
fi

if [[  "$1" != "osv-skip" ]]
then
  if ! osv-scanner -v >> /dev/null; 
  then
      echo "OSV-scanner not installed, please visit below link for more details"
      echo "https://dev.azure.com/iouring/init/_wiki/wikis/init/58/osv"
      exit 1
  fi
  set +e
  osv-scanner -r package-lock.json
fi

exit 0
